// Material Icons for the streaming app
export const ICONS = {
  // Navigation
  HOME: 'home',
  SEARCH: 'search',
  DOWNLOAD: 'file-download',
  USER: 'person',
  MENU: 'menu',
  ARROW_LEFT: 'arrow-back',
  ARROW_RIGHT: 'arrow-forward',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  CHEVRON_DOWN: 'expand-more',
  CHEVRON_UP: 'expand-less',
  EDIT: 'edit',
  SHORTS: 'video-library',

  // Media Controls
  PLAY: 'play-arrow',
  PAUSE: 'pause',
  STOP: 'stop',
  SKIP_BACK: 'skip-previous',
  SKIP_FORWARD: 'skip-next',
  VOLUME: 'volume-up',
  VOLUME_OFF: 'volume-off',
  SUBTITLES: 'subtitles',
  SUBTITLES_OFF: 'closed-caption-disabled',
  MAXIMIZE: 'fullscreen',
  MINIMIZE: 'fullscreen-exit',

  // Actions
  PLUS: 'add',
  MINUS: 'remove',
  HEART: 'favorite',
  BOOKMARK: 'bookmark',
  SHARE: 'share',
  MORE_HORIZONTAL: 'more-horiz',
  MORE_VERTICAL: 'more-vert',
  SETTINGS: 'settings',
  FILTER: 'filter-list',
  CLOSE: 'close',

  // Status
  CHECK: 'check',
  X: 'close',
  ALERT: 'error',
  ALERT_CIRCLE: 'error-outline',
  INFO: 'info',
  STAR: 'star',
  EYE: 'visibility',
  EYE_OFF: 'visibility-off',
  SUN: 'wb-sunny',
  MOOD: 'mood',
  WARNING: 'warning',
  ROCKET_LAUNCH: 'rocket-launch',
  ARTICLE: 'article',
  EARTH: 'public',
  USERS: 'group',
  HELP_OUTLINE: 'help-outline',
  HELP: 'help',
  INFO_CIRCLE: 'info',
  CAMERA_ALT: 'camera-alt',
  DASHBOARD: 'dashboard',
  LOCAL_FIRE_DEPARTMENT: 'local-fire-department',
  SCHEDULE: 'schedule',
  PLAY_CIRCLE_FILLED: 'play-circle-filled',
  CLOUD_OFF: 'cloud-off',
  LINK: 'link',
  LOGOUT: 'logout',
  CONTENT_COPY: 'content-copy',
  PLAY_CIRCLE: 'play-circle',
  DELETE_FOREVER: 'delete-forever',
  BAR_CHART: 'bar-chart',
  SEND: 'send',
  SYSTEM_UPDATE: 'system-update',
  FIBER_MANUAL_RECORD: 'fiber-manual-record',

  // Communication
  BELL: 'notifications',
  MAIL: 'mail',
  MESSAGE: 'message',
  PHONE: 'phone',
  CHAT: 'chat',

  // Files & Media
  IMAGE: 'image',
  VIDEO: 'videocam',
  FILM: 'movie',
  MUSIC: 'music-note',
  FILE: 'insert-drive-file',
  FOLDER: 'folder',

  // Connectivity
  WIFI: 'wifi',
  BLUETOOTH: 'bluetooth',
  CAST: 'cast',

  // Interface
  GRID: 'grid-on',
  LIST: 'list',
  CALENDAR: 'calendar-today',
  CLOCK: 'schedule',
  REFRESH: 'refresh',
  LOADER: 'hourglass-empty',

  // Financial
  WALLET: 'account-balance-wallet',
  ACCOUNT_BALANCE_WALLET: 'account-balance-wallet',
  ACCOUNT_BALANCE: 'account-balance',
  SHOPPING_CART: 'shopping-cart',
  TRENDING_UP: 'trending-up',
  TRENDING_DOWN: 'trending-down',
  CREDIT_CARD: 'credit-card',
  SWAP_HORIZ: 'swap-horiz',
  STARS: 'stars',

  // Additional icons
  HEART_OUTLINE: 'favorite-border',
  BOOKMARK_BORDER: 'bookmark-border',
  COMMENT: 'comment',
  CHECK_SQUARE: 'check-box',
  HARD_DRIVE: 'storage',
  TRASH: 'delete',
  CIRCLE: 'radio-button-unchecked',
  CHECK_CIRCLE: 'check-circle',
  PLAY_CIRCLE_OUTLINE: 'play-circle-outline',
  VIDEO_LIBRARY: 'video-library',
  SPEED: 'speed',
  CLEAR_ALL: 'clear-all',
  ANALYTICS: 'analytics',
  DESCRIPTION: 'description',
  FAVORITE_BORDER: 'favorite-border',
  WIFI_OFF: 'wifi-off',
  SYNC: 'sync',
  SYNC_PROBLEM: 'sync-problem',
  HIGH_QUALITY: 'high-quality',
  PLAYLIST_PLAY: 'playlist-play',
  LIVE_TV: 'live-tv',
  CATEGORY: 'category',
  LOCATION_ON: 'location-on',
  EMAIL: 'email',
  LANGUAGE: 'language',
  HISTORY: 'history',
  FAVORITE: 'favorite',
  PERSON: 'person',
  VIDEOCAM: 'videocam',
  STORAGE: 'storage',
  CLOUD_DOWNLOAD: 'cloud-download',
  SPORTS: 'sports-soccer',
  CHILD_CARE: 'child-care',
  DELETE_SWEEP: 'delete-sweep',
  AUTO_DELETE: 'auto-delete',
  CHECKLIST: 'checklist',
  FILE_DOWNLOAD: 'file-download',
  EXPLORE: 'explore',
  GRID_VIEW: 'grid-view',
  SORT: 'sort',

  // Creator Dashboard specific
  PEOPLE: 'people',
  DOWNLOAD_ARROW: 'download',
  DEVICES: 'devices',
  PHONE_ANDROID: 'phone-android',
  PHONE_IPHONE: 'phone-iphone',
  CLOUD_UPLOAD: 'cloud-upload',
  TIMER: 'timer',
  SECURITY: 'security',
  RADAR: 'radar',
  BATTERY_CHARGING_FULL: 'battery-charging-full',
  ZOOM_OUT_MAP: 'zoom-out-map',
  ARROW_LEFT_CIRCLE: 'arrow-left-circle',
  ATTACH_FILE: 'attach-file',
  MIC: 'mic',
  INBOX: 'inbox',
  TITLE: 'title',
  DIAMOND: 'diamond',
  EMOTION: 'emoji-emotions',
  LOCK: 'lock',
  MONETIZE_ON: 'attach-money',

  // Upload screen specific icons
  SD_CARD: 'sd-card',
  ADD: 'add',
  MONETIZE: 'attach-money',
  VERIFIED: 'verified',
  CHECK_ALL: 'done-all',
  PALETTE: 'palette',
  NOTIFICATIONS: 'notifications',
  CARD_GIFTCARD: 'card-giftcard',

  // Community and groups specific icons
  GROUP: 'groups',
  BOOK: 'menu-book',

  // Spred Wallet specific icons
  WITHDRAW: 'withdraw',
  ARROW_UPWARD: 'arrow-upward',
  ADD_CIRCLE: 'add-circle',
  REMOVE_CIRCLE: 'remove-circle',
  SEND: 'send',
  RECEIVE: 'swap-horiz',
  TOKEN: 'token',
  ACCOUNT_BALANCE_BANK: 'account-balance-bank',
  PAYMENT: 'payment',
  SAVINGS: 'savings',
  EXCHANGE: 'exchange',
  QR_CODE: 'qr-code',
  KEYBOARD_ARROW_UP: 'keyboard-arrow-up',
  KEYBOARD_ARROW_DOWN: 'keyboard-arrow-down',
  TOLL: 'toll',
  BAR_CHART: 'bar-chart',
  PIE_CHART: 'pie-chart',
  SHOW_CHART: 'show-chart',
  INSERT_CHART: 'insert-chart',
} as const;

export type IconName = (typeof ICONS)[keyof typeof ICONS];
